use_frameworks!

platform :ios, '8.0'

target 'XHFirstManager_Example' do
  pod 'XHFirstManager', :path => '../'

  target 'XHFirstManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
